language: python
python:
    - "3.6"
cache: pip
script:
  - ./manage.py test

before_deploy:
  - yes | pip install fandogh_cli --upgrade

deploy:
  provider: script
  script: bash deployment/scripts/deploy-to-fandogh.sh
  on:
    branch: master
